---
title: "COVID-19 Open Research Dataset Challenge (CORD-19)"
subtitle: "Exploratory Data Analysis"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(tidytext)
library(jsonlite)


metadata <- read_csv("./2020-03-13/all_sources_metadata_2020-03-13.csv")

str(metadata)

metadata %>% 
  count(license, sort = T)

metadata %>% 
  count(publish_time, sort = T)

metadata %>% 
  filter(has_full_text) %>% 
  dim()

metadata %>% 
  filter(!is.na(abstract)) %>% 
  dim()

```

# Extracting text fom all the full papers

```{r}

json_files <- dir("./2020-03-13/comm_use_subset/comm_use_subset/", full.names=T)
json_objects <- json_files[1:1000] %>%  map(read_json)

json_tbl <- tibble(json=json_objects)

article_data <- json_tbl %>% 
  hoist(
    json, 
    paper_id = "paper_id",
    title = c("metadata","title"),
    abstract = c("abstract", function(.) str_c(map_chr(.,"text"), collapse = "\n")),
    body_text = c("body_text", function(.) str_c(map_chr(.,"text"), collapse = "\n")),
    bib_entries = "bib_entries"
  ) %>% 
  select(-json) %>% 
  filter(!is.na(abstract))

rm(json_objects, json_tbl); gc()
```

## some text mining on article titles

```{r}
title_words <- article_data %>% 
  unnest_tokens(word, title) %>% 
  anti_join(stop_words, by="word") %>% 
  count(word, sort=T)

title_words %>% 
  head(20) %>% 
  mutate(word=fct_reorder(word,n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() + 
  coord_flip() +
  theme_minimal() +
  labs(title="Words that appers in many titles")
```

## text mining in the abstracts

```{r}

abstract_words <- article_data %>% 
  unnest_tokens(word, abstract ) %>% 
  anti_join(stop_words, by="word") %>% 
  count(word, sort = T)

abstract_words %>% 
  head(20) %>% 
  mutate(word=fct_reorder(word, n)) %>% 
  ggplot(aes(word,n)) +
  geom_col() +
  coord_flip() +
  theme_minimal() +
  labs(title="Words that appers in many abstracts")

```

## texting spacy.io

```{r}
# install.packages("spacyr")
library(spacyr)
# spacy_install(lang_models="https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz")
spacy_initialize("en_core_sci_sm")
```

```{r}

spacy_extract_entity("Myeloid derived suppressor cells (MDSC) are immature myeloid cells with immunosuppressive activity. They accumulate in tumor-bearing mice and humans with different types of cancer, including hepatocellular carcinoma (HCC).")

```

## Using tidytext and spacy

Tidytext can take a custom tokenization function

```{r}

tokenize_scispacy_entities <- function(text){
  spacy_extract_entity(text) %>% 
    group_by(doc_id) %>% 
    nest() %>% 
    pull(data) %>% 
    map("text")
}

tokenize_scispacy_entities(c("Myeloid derived suppressor cells (MDSC) are immature myeloid cells with immunosuppressive activity.","They accumulate in tumor-bearing mice and humans with different types of cancer, including hepatocellular carcinoma (HCC)."))


abstract_entities <- article_data %>% 
  select(paper_id, abstract) %>% 
  sample_n(2000) %>% 
  unnest_tokens(entity, abstract, token=tokenize_scispacy_entities)


abstract_entities %>% 
  head(20)

```


```{r}

abstract_entities %>% 
  count(entity, sort=T)

abstract_entities %>% 
  count(entity, sort = T) %>% 
  head(30) %>% 
  mutate(entity= fct_reorder(entity, n)) %>% 
  ggplot(aes(entity, n)) +
  geom_col() +
  coord_flip() +
  theme_minimal()

```

What are the entities that appears together?

```{r}
library(widyr)

entity_correlations <- abstract_entities %>% 
  add_count(entity) %>% 
  filter(n>=100) %>% 
  pairwise_cor(entity, paper_id, sort=T) %>% 
  head(400)

library(ggraph)
library(igraph)
library(graphlayouts)

set.seed(2020)
g <- entity_correlations %>% 
  igraph::graph_from_data_frame()

V(g)$degree <- degree(g)

g %>% 
  ggraph("stress") +
  geom_edge_link(aes(edge_alpha=correlation), col="grey66") +
  geom_node_point(aes(alpha=degree, size=degree), col="red") +
  geom_node_text(aes(label=name), repel = T) +
  theme_graph() +
  theme(legend.position = "none") +
  labs(title="Entities that often appers together in the abstract",
       subtitle="Based on the scispacy Named Entity Recognition model")

```

### References

```{r}

article_references <- article_data %>% 
  head(500) %>% 
  select(paper_id, bib_entries) %>% 
  unnest(bib_entries) %>% 
  unnest_wider(bib_entries)

article_references %>% 
  select(-authors, -other_ids) %>% 
  write_csv("./article_references.csv")
```

```{r}
article_references %>% 
  count(title, sort=T)
```




